// Static reference list of Telangana police stations (one per district).
// Single source of truth for both the internal police-portal endpoint and
// the public JRMS-provider endpoint — JRMS uses this to know which `code`
// to attach to each release alert it posts to /eprisoners_release_alerts.
export const TELANGANA_POLICE_STATIONS = [
  { code: 'PS-ADI-00', name: 'Adilabad Town PS', district: 'Adilabad' },
  { code: 'PS-BHA-10', name: 'Bhadradri Kothagudem Town PS', district: 'Bhadradri Kothagudem' },
  { code: 'PS-HYD-20', name: 'Hyderabad Town PS', district: 'Hyderabad' },
  { code: 'PS-JAG-30', name: 'Jagtial Town PS', district: 'Jagtial' },
  { code: 'PS-JAN-40', name: 'Jangaon Town PS', district: 'Jangaon' },
  { code: 'PS-JAY-50', name: 'Jayashankar Bhupalpally Town PS', district: 'Jayashankar Bhupalpally' },
  { code: 'PS-JOG-60', name: 'Jogulamba Gadwal Town PS', district: 'Jogulamba Gadwal' },
  { code: 'PS-KAM-70', name: 'Kamareddy Town PS', district: 'Kamareddy' },
  { code: 'PS-KAR-80', name: 'Karimnagar Town PS', district: 'Karimnagar' },
  { code: 'PS-KHA-90', name: 'Khammam Town PS', district: 'Khammam' },
  { code: 'PS-KUM-100', name: 'Kumuram Bheem Asifabad Town PS', district: 'Kumuram Bheem Asifabad' },
  { code: 'PS-MAH-110', name: 'Mahabubabad Town PS', district: 'Mahabubabad' },
  { code: 'PS-MAH-120', name: 'Mahabubnagar Town PS', district: 'Mahabubnagar' },
  { code: 'PS-MAN-130', name: 'Mancherial Town PS', district: 'Mancherial' },
  { code: 'PS-MED-140', name: 'Medak Town PS', district: 'Medak' },
  { code: 'PS-MED-150', name: 'Medchal-Malkajgiri Town PS', district: 'Medchal-Malkajgiri' },
  { code: 'PS-MUL-160', name: 'Mulugu Town PS', district: 'Mulugu' },
  { code: 'PS-NAG-170', name: 'Nagarkurnool Town PS', district: 'Nagarkurnool' },
  { code: 'PS-NAL-180', name: 'Nalgonda Town PS', district: 'Nalgonda' },
  { code: 'PS-NAR-190', name: 'Narayanpet Town PS', district: 'Narayanpet' },
  { code: 'PS-NIR-200', name: 'Nirmal Town PS', district: 'Nirmal' },
  { code: 'PS-NIZ-210', name: 'Nizamabad Town PS', district: 'Nizamabad' },
  { code: 'PS-PED-220', name: 'Peddapalli Town PS', district: 'Peddapalli' },
  { code: 'PS-RAJ-230', name: 'Rajanna Sircilla Town PS', district: 'Rajanna Sircilla' },
  { code: 'PS-RAN-240', name: 'Ranga Reddy Town PS', district: 'Ranga Reddy' },
  { code: 'PS-SAN-250', name: 'Sangareddy Town PS', district: 'Sangareddy' },
  { code: 'PS-SID-260', name: 'Siddipet Town PS', district: 'Siddipet' },
  { code: 'PS-SUR-270', name: 'Suryapet Town PS', district: 'Suryapet' },
  { code: 'PS-VIK-280', name: 'Vikarabad Town PS', district: 'Vikarabad' },
  { code: 'PS-WAN-290', name: 'Wanaparthy Town PS', district: 'Wanaparthy' },
  { code: 'PS-WAR-300', name: 'Warangal Rural Town PS', district: 'Warangal Rural' },
  { code: 'PS-WAR-310', name: 'Warangal Urban Town PS', district: 'Warangal Urban' },
  { code: 'PS-YAD-320', name: 'Yadadri Bhuvanagiri Town PS', district: 'Yadadri Bhuvanagiri' },
];
